// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment_GateWay.Main.Data;

#nullable disable

namespace Payment_Gateway.main.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Payment_GateWay.Main.Models.UserPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            PlanType = "Premium",
                            Price = 1000L
                        },
                        new
                        {
                            Id = 10,
                            PlanType = "Premium",
                            Price = 2000L
                        },
                        new
                        {
                            Id = 15,
                            PlanType = "Premium",
                            Price = 3000L
                        },
                        new
                        {
                            Id = 20,
                            PlanType = "Premium",
                            Price = 4000L
                        },
                        new
                        {
                            Id = 25,
                            PlanType = "Premium",
                            Price = 5000L
                        },
                        new
                        {
                            Id = 30,
                            PlanType = "Premium",
                            Price = 6000L
                        },
                        new
                        {
                            Id = 35,
                            PlanType = "Premium",
                            Price = 7000L
                        },
                        new
                        {
                            Id = 40,
                            PlanType = "Premium",
                            Price = 8000L
                        },
                        new
                        {
                            Id = 45,
                            PlanType = "Premium",
                            Price = 9000L
                        },
                        new
                        {
                            Id = 50,
                            PlanType = "Premium",
                            Price = 10000L
                        },
                        new
                        {
                            Id = 55,
                            PlanType = "Premium",
                            Price = 11000L
                        },
                        new
                        {
                            Id = 60,
                            PlanType = "Premium",
                            Price = 12000L
                        },
                        new
                        {
                            Id = 65,
                            PlanType = "Premium",
                            Price = 13000L
                        },
                        new
                        {
                            Id = 70,
                            PlanType = "Premium",
                            Price = 14000L
                        },
                        new
                        {
                            Id = 75,
                            PlanType = "Premium",
                            Price = 15000L
                        },
                        new
                        {
                            Id = 80,
                            PlanType = "Premium",
                            Price = 16000L
                        },
                        new
                        {
                            Id = 85,
                            PlanType = "Premium",
                            Price = 17000L
                        },
                        new
                        {
                            Id = 90,
                            PlanType = "Premium",
                            Price = 18000L
                        },
                        new
                        {
                            Id = 95,
                            PlanType = "Premium",
                            Price = 19000L
                        },
                        new
                        {
                            Id = 100,
                            PlanType = "Premium",
                            Price = 20000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
